import React, { useState } from 'react';
import { X, PlusCircle, Sparkles, ShieldCheck, Check, Building2 } from 'lucide-react';
import { CITIES_DATA, PROPERTY_TYPES } from '../data/citiesAndLocalities';

export default function PostPropertyModal({ onClose, onAddProperty }) {
  const [step, setStep] = useState(1);
  const [title, setTitle] = useState('');
  const [city, setCity] = useState('Bengaluru');
  const [locality, setLocality] = useState('');
  const [bhk, setBhk] = useState(2);
  const [priceVal, setPriceVal] = useState(7500000); // 75 Lacs default
  const [carpetArea, setCarpetArea] = useState(1150);
  const [facing, setFacing] = useState('East Facing');
  const [reraId, setReraId] = useState('PRM/KA/RERA/1251/310/PR/220101/004321');
  const [sellerType, setSellerType] = useState('Owner');
  const [sellerName, setSellerName] = useState('');
  const [sellerPhone, setSellerPhone] = useState('');
  const [description, setDescription] = useState('');
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  // Simple, deterministic AI description auto-generator for Indian real estate
  const handleAutoGenerateDescription = () => {
    setIsGeneratingAi(true);
    setTimeout(() => {
      const generated = `Well-maintained ${bhk} BHK ${facing} apartment located in prime ${locality || 'locality'}, ${city}. Features excellent cross-ventilation, spacious balconies, modular kitchen fittings, 24x7 water supply, covered car parking, and RERA compliance. Close to tech parks, metro station, reputed schools, and hospitals. Ideal for families and professionals seeking high rental return and high capital appreciation.`;
      setDescription(generated);
      setIsGeneratingAi(false);
    }, 400);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const priceDisplay = priceVal >= 10000000 
      ? `₹${(priceVal / 10000000).toFixed(2)} Cr` 
      : `₹${(priceVal / 100000).toFixed(0)} Lac`;
      
    const newProperty = {
      id: `ez-user-${Date.now()}`,
      title: title || `${bhk} BHK Apartment in ${locality || city}`,
      listingType: 'buy',
      propertyType: 'apartment',
      city,
      locality: locality || 'Central',
      address: `${locality || 'Main Road'}, ${city}`,
      priceVal: Number(priceVal),
      priceDisplay,
      pricePerSqFt: Math.round(Number(priceVal) / Number(carpetArea)),
      bhk: Number(bhk),
      bathrooms: Number(bhk),
      balconies: 1,
      carpetArea: Number(carpetArea),
      builtUpArea: Math.round(Number(carpetArea) * 1.15),
      floor: '5th of 12 Floors',
      facing,
      possessionStatus: 'Ready to Move',
      ageOfProperty: '1 Year',
      maintenanceMonthly: 3000,
      reraId: reraId || 'PRM/KA/RERA/VERIFIED/2026',
      isReraVerified: true,
      sellerType,
      sellerName: sellerName || 'Verified Property Dealer',
      sellerPhone: sellerPhone || '+91 98450 00000',
      sellerWhatsApp: '919845000000',
      images: [
        'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80',
        'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'
      ],
      floorPlanUrl: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1000&q=80',
      amenities: ['Power Backup', 'Lift', 'Security Guard', 'Car Parking'],
      localityAdvantages: [{ name: 'Nearest Metro Station', distance: '1.0 km' }],
      aiFairPriceEstimate: {
        min: priceDisplay,
        max: priceDisplay,
        valuationStatus: 'Fair Price',
        localityGrowth5Yr: '+20.0%'
      },
      description: description || 'Spacious property with excellent connectivity and modern amenities.'
    };

    onAddProperty(newProperty);
    setSubmitted(true);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white rounded-xl max-w-xl w-full p-5 sm:p-6 shadow-2xl border border-slate-200 relative my-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 mb-5">
          <div className="flex items-center gap-2">
            <div className="bg-amber-100 text-amber-900 p-2 rounded-lg">
              <PlusCircle className="w-5 h-5 text-amber-700" />
            </div>
            <div>
              <h3 className="text-lg font-extrabold text-slate-900">Post Free Property Listing</h3>
              <p className="text-xs text-slate-500">Zero charges for owners & brokers • Instant RERA Verification</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-md hover:bg-slate-100 text-slate-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        {submitted ? (
          <div className="text-center py-8 space-y-3">
            <div className="w-12 h-12 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center mx-auto">
              <Check className="w-6 h-6 stroke-[3]" />
            </div>
            <h4 className="text-lg font-extrabold text-slate-900">Listing Published Successfully!</h4>
            <p className="text-xs text-slate-600 max-w-sm mx-auto">
              Your property is now live on EZ HOMES and visible to thousands of buyers and tenants across India.
            </p>
            <button 
              onClick={onClose} 
              className="bg-brand-700 hover:bg-brand-800 text-white font-bold text-xs px-6 py-2.5 rounded mt-4"
            >
              Back to Marketplace
            </button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4 text-xs font-semibold text-slate-700">
            
            {/* Title & City */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">City</label>
                <select 
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  {CITIES_DATA.map(c => (
                    <option key={c.id} value={c.name}>{c.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Locality / Area Name</label>
                <input 
                  type="text" 
                  required
                  placeholder="e.g. Whitefield / HSR Layout"
                  value={locality}
                  onChange={(e) => setLocality(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* BHK & Carpet Area */}
            <div className="grid grid-cols-3 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">BHK Count</label>
                <select 
                  value={bhk}
                  onChange={(e) => setBhk(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  <option value={1}>1 BHK</option>
                  <option value={2}>2 BHK</option>
                  <option value={3}>3 BHK</option>
                  <option value={4}>4+ BHK</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Carpet Area (sq.ft)</label>
                <input 
                  type="number" 
                  required
                  value={carpetArea}
                  onChange={(e) => setCarpetArea(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Facing Direction</label>
                <select 
                  value={facing}
                  onChange={(e) => setFacing(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  <option value="East Facing">East Facing</option>
                  <option value="North Facing">North Facing</option>
                  <option value="North-East">North-East</option>
                  <option value="West Facing">West Facing</option>
                </select>
              </div>
            </div>

            {/* Price Input */}
            <div>
              <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Expected Total Price (INR)</label>
              <div className="flex items-center gap-2">
                <input 
                  type="number" 
                  required
                  step="100000"
                  value={priceVal}
                  onChange={(e) => setPriceVal(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-sm font-extrabold text-slate-900 focus:outline-none"
                />
                <span className="text-xs font-bold text-brand-700 shrink-0 bg-blue-50 px-2 py-1.5 rounded border border-blue-200">
                  {priceVal >= 10000000 ? `₹${(priceVal / 10000000).toFixed(2)} Cr` : `₹${(priceVal / 100000).toFixed(0)} Lac`}
                </span>
              </div>
            </div>

            {/* RERA ID & Seller Type */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">RERA Reg Number (If Broker/Builder)</label>
                <input 
                  type="text" 
                  value={reraId}
                  onChange={(e) => setReraId(e.target.value)}
                  placeholder="e.g. PRM/KA/RERA/..."
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Listing Posted By</label>
                <select 
                  value={sellerType}
                  onChange={(e) => setSellerType(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  <option value="Owner">Direct Owner (0 Brokerage)</option>
                  <option value="Broker">Verified Broker / Agent</option>
                  <option value="Builder">Builder / Developer</option>
                </select>
              </div>
            </div>

            {/* Contact Details */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Your Name</label>
                <input 
                  type="text" 
                  required
                  placeholder="Full Name"
                  value={sellerName}
                  onChange={(e) => setSellerName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Phone Number</label>
                <input 
                  type="tel" 
                  required
                  placeholder="+91 98450 12345"
                  value={sellerPhone}
                  onChange={(e) => setSellerPhone(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* AI Description Generator Block */}
            <div className="bg-slate-50 p-3 rounded-lg border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-[10px] font-bold text-slate-500 uppercase">Property Description</label>
                <button 
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={isGeneratingAi}
                  className="text-[11px] font-bold text-amber-700 bg-amber-50 hover:bg-amber-100 px-2.5 py-1 rounded border border-amber-300 flex items-center gap-1 transition-colors"
                >
                  <Sparkles className="w-3 h-3 text-amber-600" />
                  <span>{isGeneratingAi ? 'Auto-writing...' : 'AI Auto-Generate Description'}</span>
                </button>
              </div>
              <textarea 
                rows={3}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe key features, society amenities, and nearby metro station..."
                className="w-full bg-white border border-slate-300 rounded p-2 text-xs text-slate-900 focus:outline-none"
              />
            </div>

            <button 
              type="submit" 
              className="w-full bg-amber-600 hover:bg-amber-700 text-white font-extrabold text-xs py-3 rounded transition-colors uppercase tracking-wider shadow-sm"
            >
              Publish Free Property Listing
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
