import React, { useState } from 'react';
import { X, PlusCircle, Sparkles, Check, Upload, Image as ImageIcon } from 'lucide-react';
import { CITIES_DATA } from '../data/citiesAndLocalities';
import { supabaseService } from '../services/supabaseService';
import { supabase } from '../lib/supabase';

export default function PostPropertyModal({ onClose, onAddProperty, currentUser, userRole }) {
  const [title, setTitle] = useState('');
  const [city, setCity] = useState('Jammu');
  const [locality, setLocality] = useState('');
  const [bhk, setBhk] = useState(2);
  const [priceVal, setPriceVal] = useState(7500000); // 75 Lacs default
  const [carpetArea, setCarpetArea] = useState(1150);
  const [facing, setFacing] = useState('East Facing');
  const [reraId, setReraId] = useState('JKRERA/JM/AGENT/2026/00123');
  const [sellerType, setSellerType] = useState('Owner');
  const [sellerName, setSellerName] = useState(currentUser?.email ? currentUser.email.split('@')[0] : 'Property Owner');
  const [sellerPhone, setSellerPhone] = useState('+91 94191 00000');
  const [description, setDescription] = useState('');
  const [selectedFiles, setSelectedFiles] = useState([]);
  const [imagePreviews, setImagePreviews] = useState([]);

  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  // AI description auto-generator
  const handleAutoGenerateDescription = () => {
    setIsGeneratingAi(true);
    setTimeout(() => {
      const generated = `Well-maintained ${bhk} BHK ${facing} apartment located in prime ${locality || 'locality'}, ${city}. Features excellent cross-ventilation, spacious balconies, modular kitchen fittings, 24x7 water supply, covered car parking, and RERA compliance. Close to tech parks, market center, reputed schools, and hospitals. Ideal for families and professionals.`;
      setDescription(generated);
      setIsGeneratingAi(false);
    }, 400);
  };

  const handleImageFileChange = (e) => {
    const files = Array.from(e.target.files);
    if (!files.length) return;

    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    const maxSize = 5 * 1024 * 1024; // 5MB

    const invalidType = files.find(f => !allowedTypes.includes(f.type.toLowerCase()));
    if (invalidType) {
      setErrorMessage(`Invalid file type: ${invalidType.name}. Only JPG, JPEG, PNG, and WEBP formats are supported.`);
      return;
    }

    const oversized = files.find(f => f.size > maxSize);
    if (oversized) {
      setErrorMessage(`File too large: ${oversized.name}. Maximum allowed image size is 5MB.`);
      return;
    }

    setErrorMessage('');
    setSelectedFiles(files);
    const previews = files.map(file => URL.createObjectURL(file));
    setImagePreviews(previews);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');
    setIsSubmitting(true);

    try {
      const priceDisplay = priceVal >= 10000000 
        ? `₹${(priceVal / 10000000).toFixed(2)} Cr` 
        : `₹${(priceVal / 100000).toFixed(0)} Lac`;
        
      const propertyInput = {
        title: title || `${bhk} BHK Apartment in ${locality || city}`,
        listingType: 'buy',
        propertyType: 'apartment',
        city,
        locality: locality || 'Gandhi Nagar',
        address: `${locality || 'Main Road'}, ${city}`,
        priceVal: Number(priceVal),
        priceDisplay,
        carpetArea: Number(carpetArea),
        bhk: Number(bhk),
        bathrooms: Number(bhk),
        floor: '2nd Floor',
        facing,
        reraId,
        sellerType,
        sellerName,
        sellerPhone,
        description,
        amenities: ['Power Backup', 'Lift', 'Security Guard', 'Car Parking']
      };

      // 1. Post Property to Supabase (default status = pending_review)
      const createdProp = await supabaseService.postProperty(
        propertyInput, 
        currentUser?.id || null, 
        userRole
      );

      // 2. Upload Property Images to Supabase Storage if files selected
      if (selectedFiles.length > 0 && createdProp && createdProp.id) {
        for (let i = 0; i < selectedFiles.length; i++) {
          try {
            await supabaseService.uploadPropertyImage(
              selectedFiles[i], 
              createdProp.id, 
              i === 0
            );
          } catch (storageErr) {
            console.warn('Image upload failed, continuing with property creation:', storageErr.message);
          }
        }
      }

      // Notify parent component
      onAddProperty({
        ...propertyInput,
        id: createdProp.id || `ez-user-${Date.now()}`,
        status: 'pending_review',
        isReraVerified: true,
        images: imagePreviews.length > 0 ? imagePreviews : [
          'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80'
        ]
      });

      setSubmitted(true);
    } catch (err) {
      setErrorMessage(err.message || 'Failed to submit property listing. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white rounded-xl max-w-xl w-full p-5 sm:p-6 shadow-2xl border border-slate-200 relative my-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 mb-5">
          <div className="flex items-center gap-2">
            <div className="bg-amber-100 text-amber-900 p-2 rounded-lg">
              <PlusCircle className="w-5 h-5 text-amber-700" />
            </div>
            <div>
              <h3 className="text-lg font-extrabold text-slate-900">Submit Property for Admin Approval</h3>
              <p className="text-xs text-slate-500">Submit property details for Trustify Homes Admin verification & listing approval</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-md hover:bg-slate-100 text-slate-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        {submitted ? (
          <div className="text-center py-8 space-y-3">
            <div className="w-12 h-12 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center mx-auto">
              <Check className="w-6 h-6 stroke-[3]" />
            </div>
            <h4 className="text-lg font-extrabold text-slate-900">Listing Submitted for Review!</h4>
            <p className="text-xs text-slate-600 max-w-sm mx-auto">
              Your property has been saved to the database with status <strong className="text-amber-700 font-extrabold">pending_review</strong>. Once approved by admin, it will be published to the public marketplace.
            </p>
            <button 
              onClick={onClose} 
              className="bg-brand-700 hover:bg-brand-800 text-white font-bold text-xs px-6 py-2.5 rounded mt-4"
            >
              Back to Marketplace
            </button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4 text-xs font-semibold text-slate-700">
            
            {errorMessage && (
              <div className="p-3 bg-red-50 text-red-700 rounded border border-red-200 text-xs">
                {errorMessage}
              </div>
            )}

            {/* Title & City */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">City</label>
                <select 
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  {CITIES_DATA.map(c => (
                    <option key={c.id} value={c.name}>{c.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Locality / Area Name</label>
                <input 
                  type="text" 
                  required
                  placeholder="e.g. Gandhi Nagar / Trikuta Nagar"
                  value={locality}
                  onChange={(e) => setLocality(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* BHK & Carpet Area */}
            <div className="grid grid-cols-3 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">BHK Count</label>
                <select 
                  value={bhk}
                  onChange={(e) => setBhk(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  <option value={1}>1 BHK</option>
                  <option value={2}>2 BHK</option>
                  <option value={3}>3 BHK</option>
                  <option value={4}>4+ BHK</option>
                </select>
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Carpet Area (sq.ft)</label>
                <input 
                  type="number" 
                  required
                  value={carpetArea}
                  onChange={(e) => setCarpetArea(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Facing Direction</label>
                <select 
                  value={facing}
                  onChange={(e) => setFacing(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  <option value="East Facing">East Facing</option>
                  <option value="North Facing">North Facing</option>
                  <option value="North-East">North-East</option>
                  <option value="West Facing">West Facing</option>
                </select>
              </div>
            </div>

            {/* Price Input */}
            <div>
              <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Expected Total Price (INR)</label>
              <div className="flex items-center gap-2">
                <input 
                  type="number" 
                  required
                  step="100000"
                  value={priceVal}
                  onChange={(e) => setPriceVal(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-sm font-extrabold text-slate-900 focus:outline-none"
                />
                <span className="text-xs font-bold text-brand-700 shrink-0 bg-blue-50 px-2 py-1.5 rounded border border-blue-200">
                  {priceVal >= 10000000 ? `₹${(priceVal / 10000000).toFixed(2)} Cr` : `₹${(priceVal / 100000).toFixed(0)} Lac`}
                </span>
              </div>
            </div>

            {/* Image Upload Field (Supabase Storage) */}
            <div className="bg-slate-50 p-3 rounded-lg border border-slate-200 space-y-2">
              <label className="block text-slate-500 uppercase tracking-wider text-[10px]">
                Property Photos (Upload to Supabase Storage)
              </label>
              <div className="flex items-center gap-3">
                <label className="cursor-pointer bg-white border border-slate-300 hover:border-slate-400 px-3 py-2 rounded text-xs font-bold text-slate-700 flex items-center gap-1.5 transition-colors">
                  <Upload className="w-4 h-4 text-brand-600" />
                  <span>Choose Images (JPG, PNG, WEBP)</span>
                  <input 
                    type="file" 
                    multiple 
                    accept="image/jpeg,image/jpg,image/png,image/webp" 
                    onChange={handleImageFileChange}
                    className="hidden" 
                  />
                </label>
                <span className="text-[11px] text-slate-500 font-normal">
                  {selectedFiles.length > 0 ? `${selectedFiles.length} images selected` : 'No files selected'}
                </span>
              </div>

              {/* Image Previews */}
              {imagePreviews.length > 0 && (
                <div className="flex items-center gap-2 overflow-x-auto pt-2">
                  {imagePreviews.map((src, idx) => (
                    <img key={idx} src={src} alt="preview" className="w-14 h-14 object-cover rounded border border-slate-300 shrink-0" />
                  ))}
                </div>
              )}
            </div>

            {/* Contact Details */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Your Name</label>
                <input 
                  type="text" 
                  required
                  placeholder="Full Name"
                  value={sellerName}
                  onChange={(e) => setSellerName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Phone Number</label>
                <input 
                  type="tel" 
                  required
                  placeholder="+91 94191 00000"
                  value={sellerPhone}
                  onChange={(e) => setSellerPhone(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* AI Description Generator Block */}
            <div className="bg-slate-50 p-3 rounded-lg border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-[10px] font-bold text-slate-500 uppercase">Property Description</label>
                <button 
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={isGeneratingAi}
                  className="text-[11px] font-bold text-amber-700 bg-amber-50 hover:bg-amber-100 px-2.5 py-1 rounded border border-amber-300 flex items-center gap-1 transition-colors"
                >
                  <Sparkles className="w-3 h-3 text-amber-600" />
                  <span>{isGeneratingAi ? 'Auto-writing...' : 'AI Auto-Generate Description'}</span>
                </button>
              </div>
              <textarea 
                rows={3}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe key features, society amenities, and nearby metro station..."
                className="w-full bg-white border border-slate-300 rounded p-2 text-xs text-slate-900 focus:outline-none"
              />
            </div>

            <button 
              type="submit" 
              disabled={isSubmitting}
              className="w-full bg-amber-600 hover:bg-amber-700 text-white font-extrabold text-xs py-3 rounded transition-colors uppercase tracking-wider shadow-sm disabled:opacity-50"
            >
              {isSubmitting ? 'Uploading to Supabase DB & Storage...' : 'Publish Property Listing'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
