import React, { useState } from 'react';
import { X, PlusCircle, Sparkles, Check, Upload, Image as ImageIcon, GraduationCap, Home } from 'lucide-react';
import { CITIES_DATA, JAMMU_COLLEGES } from '../data/citiesAndLocalities';
import { supabaseService } from '../services/supabaseService';

export default function PostPropertyModal({ onClose, onAddProperty, currentUser, userRole }) {
  const [listingType, setListingType] = useState('buy'); // buy | rent | pg | plot
  const [title, setTitle] = useState('');
  const [city, setCity] = useState('Jammu');
  const [locality, setLocality] = useState('');
  const [bhk, setBhk] = useState(2);
  const [priceVal, setPriceVal] = useState(7500000); // 75 Lacs default for buy, ₹7,500 default for PG/rent
  const [carpetArea, setCarpetArea] = useState(1150);
  const [facing, setFacing] = useState('East Facing');
  const [reraId, setReraId] = useState('JKRERA/JM/AGENT/2026/00123');
  const [sellerType, setSellerType] = useState('Owner');
  const [sellerName, setSellerName] = useState(currentUser?.email ? currentUser.email.split('@')[0] : 'Property Owner');
  const [sellerPhone, setSellerPhone] = useState('+91 94191 00000');
  const [description, setDescription] = useState('');
  
  // PG Specific State
  const [pgGender, setPgGender] = useState('Boys');
  const [pgRoomType, setPgRoomType] = useState('2 Sharing');
  const [availableBeds, setAvailableBeds] = useState(3);
  const [foodIncluded, setFoodIncluded] = useState(true);
  const [selectedCollegeId, setSelectedCollegeId] = useState('miet');

  const [selectedFiles, setSelectedFiles] = useState([]);
  const [imagePreviews, setImagePreviews] = useState([]);

  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const handleTabChange = (type) => {
    setListingType(type);
    if (type === 'pg') {
      setPriceVal(7500);
      setTitle('Sunrise Student PG near College');
    } else if (type === 'rent') {
      setPriceVal(18000);
    } else if (type === 'plot') {
      setPriceVal(9500000);
    } else {
      setPriceVal(7500000);
    }
  };

  // AI description auto-generator
  const handleAutoGenerateDescription = () => {
    setIsGeneratingAi(true);
    setTimeout(() => {
      let generated = '';
      if (listingType === 'pg') {
        const col = JAMMU_COLLEGES.find(c => c.id === selectedCollegeId);
        generated = `Hygienic and secure ${pgGender} Student PG offering ${pgRoomType} accommodation located near ${col ? col.name : 'college'}. Includes 3 daily home-cooked meals, 100 Mbps fiber Wi-Fi, study desks, attached bath, laundry facilities, and 24x7 security guard with CCTV.`;
      } else {
        generated = `Well-maintained ${bhk} BHK ${facing} ${listingType === 'rent' ? 'rental home' : 'apartment'} located in prime ${locality || 'locality'}, ${city}. Features excellent cross-ventilation, spacious balconies, modular kitchen fittings, 24x7 water supply, covered car parking, and RERA compliance. Close to tech parks, market center, reputed schools, and hospitals.`;
      }
      setDescription(generated);
      setIsGeneratingAi(false);
    }, 400);
  };

  const handleImageFileChange = (e) => {
    const files = Array.from(e.target.files);
    if (!files.length) return;

    const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];
    const maxSize = 5 * 1024 * 1024; // 5MB limit

    const invalidType = files.find(f => !allowedTypes.includes(f.type.toLowerCase()));
    if (invalidType) {
      setErrorMessage(`Invalid file format: ${invalidType.name}. Only JPG, JPEG, PNG, and WEBP are supported.`);
      return;
    }

    const oversized = files.find(f => f.size > maxSize);
    if (oversized) {
      setErrorMessage(`File exceeds 5MB limit: ${oversized.name}. Please select smaller images.`);
      return;
    }

    setErrorMessage('');
    setSelectedFiles(files);
    const previews = files.map(file => URL.createObjectURL(file));
    setImagePreviews(previews);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');

    // Requirement 29 Validation Quality Check
    if (!title.trim()) {
      setErrorMessage('Listing Title / PG Name is required.');
      return;
    }
    if (!locality.trim()) {
      setErrorMessage('Locality / Area Name is required.');
      return;
    }
    if (!priceVal || priceVal <= 0) {
      setErrorMessage('Valid Rent / Price is required.');
      return;
    }
    if (!description.trim()) {
      setErrorMessage('Listing Description is required.');
      return;
    }

    setIsSubmitting(true);

    try {
      let priceDisplay = '';
      if (listingType === 'pg' || listingType === 'rent') {
        priceDisplay = `₹${Number(priceVal).toLocaleString('en-IN')} / mo`;
      } else {
        priceDisplay = priceVal >= 10000000 
          ? `₹${(priceVal / 10000000).toFixed(2)} Cr` 
          : `₹${(priceVal / 100000).toFixed(0)} Lac`;
      }

      const col = JAMMU_COLLEGES.find(c => c.id === selectedCollegeId);
        
      const propertyInput = {
        title: title || (listingType === 'pg' ? 'Student PG' : `${bhk} BHK Apartment`),
        listingType,
        propertyType: listingType === 'pg' ? 'pg' : (listingType === 'plot' ? 'plot' : 'apartment'),
        city,
        locality: locality || 'Gandhi Nagar',
        address: `${locality || 'Main Road'}, ${city}`,
        priceVal: Number(priceVal),
        priceDisplay,
        carpetArea: Number(carpetArea),
        bhk: Number(bhk),
        bathrooms: Number(bhk),
        floor: '1st Floor',
        facing,
        reraId,
        sellerType,
        sellerName,
        sellerPhone,
        description,
        pgGender,
        roomType: pgRoomType,
        availableBeds: Number(availableBeds),
        foodIncluded,
        collegeId: selectedCollegeId,
        collegeName: col ? col.name : 'MIET Jammu',
        collegeDistanceKm: 0.5,
        amenities: listingType === 'pg' 
          ? ['Wi-Fi', 'AC', 'Power Backup', 'Water Supply', 'Security', 'CCTV', 'Mess / Food Included', 'Laundry']
          : ['Power Backup', 'Lift', 'Security Guard', 'Car Parking']
      };

      // 1. Post Property to Supabase (default status = pending_review)
      const createdProp = await supabaseService.postProperty(
        propertyInput, 
        currentUser?.id || null, 
        userRole
      );

      // 2. Upload Property Images to Supabase Storage if files selected
      if (selectedFiles.length > 0 && createdProp && createdProp.id) {
        for (let i = 0; i < selectedFiles.length; i++) {
          try {
            await supabaseService.uploadPropertyImage(
              selectedFiles[i], 
              createdProp.id, 
              i === 0
            );
          } catch (storageErr) {
            console.warn('Image upload failed, continuing with property creation:', storageErr.message);
          }
        }
      }

      // Notify parent component
      onAddProperty({
        ...propertyInput,
        id: createdProp.id || `ez-user-${Date.now()}`,
        status: 'pending_review',
        isReraVerified: true,
        images: imagePreviews.length > 0 ? imagePreviews : [
          listingType === 'pg' 
            ? 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1000&q=80'
            : 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80'
        ]
      });

      setSubmitted(true);
    } catch (err) {
      setErrorMessage(err.message || 'Failed to submit property listing. Please try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white rounded-xl max-w-xl w-full p-5 sm:p-6 shadow-2xl border border-slate-200 relative my-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 mb-4">
          <div className="flex items-center gap-2">
            <div className="bg-amber-100 text-amber-900 p-2 rounded-lg">
              <PlusCircle className="w-5 h-5 text-amber-700" />
            </div>
            <div>
              <h3 className="text-lg font-extrabold text-slate-900">Post Listing for Admin Moderation</h3>
              <p className="text-xs text-slate-500">Submit property or PG details for Trustify Homes verification</p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-md hover:bg-slate-100 text-slate-500">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Listing Type Switcher (Buy / Rent / PG / Plot) */}
        <div className="flex gap-1.5 bg-slate-100 p-1.5 rounded-lg mb-4 text-xs font-bold">
          <button
            type="button"
            onClick={() => handleTabChange('buy')}
            className={`flex-1 py-1.5 rounded transition-all text-center ${
              listingType === 'buy' ? 'bg-slate-900 text-white shadow-xs' : 'text-slate-700 hover:bg-slate-200'
            }`}
          >
            Buy / Sale
          </button>

          <button
            type="button"
            onClick={() => handleTabChange('rent')}
            className={`flex-1 py-1.5 rounded transition-all text-center ${
              listingType === 'rent' ? 'bg-slate-900 text-white shadow-xs' : 'text-slate-700 hover:bg-slate-200'
            }`}
          >
            Rent / Lease
          </button>

          <button
            type="button"
            onClick={() => handleTabChange('pg')}
            className={`flex-1 py-1.5 rounded transition-all text-center flex items-center justify-center gap-1 ${
              listingType === 'pg' ? 'bg-purple-900 text-white shadow-xs' : 'text-purple-950 bg-purple-100 hover:bg-purple-200'
            }`}
          >
            <GraduationCap className="w-3.5 h-3.5" />
            <span>PG / Hostel</span>
          </button>

          <button
            type="button"
            onClick={() => handleTabChange('plot')}
            className={`flex-1 py-1.5 rounded transition-all text-center ${
              listingType === 'plot' ? 'bg-slate-900 text-white shadow-xs' : 'text-slate-700 hover:bg-slate-200'
            }`}
          >
            Plot / Land
          </button>
        </div>

        {submitted ? (
          <div className="text-center py-8 space-y-3">
            <div className="w-12 h-12 bg-emerald-100 text-emerald-700 rounded-full flex items-center justify-center mx-auto">
              <Check className="w-6 h-6 stroke-[3]" />
            </div>
            <h4 className="text-lg font-extrabold text-slate-900">Listing Submitted for Review!</h4>
            <p className="text-xs text-slate-600 max-w-sm mx-auto">
              Your listing has been saved to the database with status <strong className="text-amber-700 font-extrabold">pending_review</strong>. Once approved by admin, it will be published to the public marketplace.
            </p>
            <button 
              onClick={onClose} 
              className="bg-brand-700 hover:bg-brand-800 text-white font-bold text-xs px-6 py-2.5 rounded mt-4"
            >
              Back to Marketplace
            </button>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="space-y-4 text-xs font-semibold text-slate-700">
            
            {errorMessage && (
              <div className="p-3 bg-red-50 text-red-700 rounded border border-red-200 text-xs">
                {errorMessage}
              </div>
            )}

            {/* Title / PG Name */}
            <div>
              <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">
                {listingType === 'pg' ? 'PG / Hostel Name *' : 'Listing Title *'}
              </label>
              <input 
                type="text" 
                required
                placeholder={listingType === 'pg' ? 'e.g. Sunrise Student PG near MIET' : 'e.g. Luxury 3 BHK Kothi in Gandhi Nagar'}
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
              />
            </div>

            {/* City & Locality */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">City</label>
                <select 
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                >
                  {CITIES_DATA.map(c => (
                    <option key={c.id} value={c.name}>{c.name}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Locality / Area Name *</label>
                <input 
                  type="text" 
                  required
                  placeholder="e.g. Kot Bhalwal / Gandhi Nagar"
                  value={locality}
                  onChange={(e) => setLocality(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* Conditional Form Fields for PG vs Standard Property */}
            {listingType === 'pg' ? (
              <div className="space-y-3 bg-purple-50/50 p-3 rounded-lg border border-purple-200">
                <div className="grid grid-cols-3 gap-3">
                  <div>
                    <label className="block text-purple-900 uppercase tracking-wider mb-1 text-[10px]">Gender / Category</label>
                    <select 
                      value={pgGender}
                      onChange={(e) => setPgGender(e.target.value)}
                      className="w-full bg-white border border-purple-300 rounded px-2.5 py-1.5 text-xs font-bold text-slate-900"
                    >
                      <option value="Boys">Boys PG</option>
                      <option value="Girls">Girls PG</option>
                      <option value="Co-living">Co-living / Unisex</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-purple-900 uppercase tracking-wider mb-1 text-[10px]">Room Type</label>
                    <select 
                      value={pgRoomType}
                      onChange={(e) => setPgRoomType(e.target.value)}
                      className="w-full bg-white border border-purple-300 rounded px-2.5 py-1.5 text-xs font-bold text-slate-900"
                    >
                      <option value="Single">Single Room</option>
                      <option value="2 Sharing">2 Sharing</option>
                      <option value="3 Sharing">3 Sharing</option>
                      <option value="Dormitory">Dormitory</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-purple-900 uppercase tracking-wider mb-1 text-[10px]">Available Beds</label>
                    <input 
                      type="number"
                      min={1}
                      value={availableBeds}
                      onChange={(e) => setAvailableBeds(Number(e.target.value))}
                      className="w-full bg-white border border-purple-300 rounded px-2.5 py-1.5 text-xs font-bold text-slate-900"
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-purple-900 uppercase tracking-wider mb-1 text-[10px]">Nearby College Campus</label>
                    <select 
                      value={selectedCollegeId}
                      onChange={(e) => setSelectedCollegeId(e.target.value)}
                      className="w-full bg-white border border-purple-300 rounded px-2.5 py-1.5 text-xs font-bold text-slate-900"
                    >
                      {JAMMU_COLLEGES.map(col => (
                        <option key={col.id} value={col.id}>{col.name}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-purple-900 uppercase tracking-wider mb-1 text-[10px]">Mess & Meal Service</label>
                    <select 
                      value={foodIncluded ? 'yes' : 'no'}
                      onChange={(e) => setFoodIncluded(e.target.value === 'yes')}
                      className="w-full bg-white border border-purple-300 rounded px-2.5 py-1.5 text-xs font-bold text-slate-900"
                    >
                      <option value="yes">Food Included (3 Meals Daily)</option>
                      <option value="no">Self Cooking / No Meals</option>
                    </select>
                  </div>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-3 gap-3">
                <div>
                  <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">BHK Count</label>
                  <select 
                    value={bhk}
                    onChange={(e) => setBhk(Number(e.target.value))}
                    className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                  >
                    <option value={1}>1 BHK</option>
                    <option value={2}>2 BHK</option>
                    <option value={3}>3 BHK</option>
                    <option value={4}>4+ BHK</option>
                  </select>
                </div>

                <div>
                  <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Carpet Area (sq.ft)</label>
                  <input 
                    type="number" 
                    required
                    value={carpetArea}
                    onChange={(e) => setCarpetArea(Number(e.target.value))}
                    className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                  />
                </div>

                <div>
                  <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Facing Direction</label>
                  <select 
                    value={facing}
                    onChange={(e) => setFacing(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs font-bold text-slate-800 focus:outline-none"
                  >
                    <option value="East Facing">East Facing</option>
                    <option value="North Facing">North Facing</option>
                    <option value="North-East">North-East</option>
                    <option value="West Facing">West Facing</option>
                  </select>
                </div>
              </div>
            )}

            {/* Price / Rent Input */}
            <div>
              <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">
                {listingType === 'pg' || listingType === 'rent' ? 'Monthly Rent (INR/month) *' : 'Expected Total Price (INR) *'}
              </label>
              <div className="flex items-center gap-2">
                <input 
                  type="number" 
                  required
                  step={listingType === 'pg' || listingType === 'rent' ? '500' : '100000'}
                  value={priceVal}
                  onChange={(e) => setPriceVal(Number(e.target.value))}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-sm font-extrabold text-slate-900 focus:outline-none"
                />
                <span className="text-xs font-bold text-brand-700 shrink-0 bg-blue-50 px-2 py-1.5 rounded border border-blue-200">
                  {listingType === 'pg' || listingType === 'rent' 
                    ? `₹${priceVal.toLocaleString('en-IN')} / mo` 
                    : (priceVal >= 10000000 ? `₹${(priceVal / 10000000).toFixed(2)} Cr` : `₹${(priceVal / 100000).toFixed(0)} Lac`)}
                </span>
              </div>
            </div>

            {/* Image Upload Field (Supabase Storage) */}
            <div className="bg-slate-50 p-3 rounded-lg border border-slate-200 space-y-2">
              <label className="block text-slate-500 uppercase tracking-wider text-[10px]">
                Listing Photos (Upload to Supabase Storage)
              </label>
              <div className="flex items-center gap-3">
                <label className="cursor-pointer bg-white border border-slate-300 hover:border-slate-400 px-3 py-2 rounded text-xs font-bold text-slate-700 flex items-center gap-1.5 transition-colors">
                  <Upload className="w-4 h-4 text-brand-600" />
                  <span>Choose Images (JPG, PNG, WEBP)</span>
                  <input 
                    type="file" 
                    multiple 
                    accept="image/jpeg,image/jpg,image/png,image/webp" 
                    onChange={handleImageFileChange}
                    className="hidden" 
                  />
                </label>
                <span className="text-[11px] text-slate-500 font-normal">
                  {selectedFiles.length > 0 ? `${selectedFiles.length} images selected` : 'No files selected'}
                </span>
              </div>

              {/* Image Previews */}
              {imagePreviews.length > 0 && (
                <div className="flex items-center gap-2 overflow-x-auto pt-2">
                  {imagePreviews.map((src, idx) => (
                    <img key={idx} src={src} alt="preview" className="w-14 h-14 object-cover rounded border border-slate-300 shrink-0" />
                  ))}
                </div>
              )}
            </div>

            {/* Contact Details */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Contact Name</label>
                <input 
                  type="text" 
                  required
                  placeholder="Full Name"
                  value={sellerName}
                  onChange={(e) => setSellerName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-slate-500 uppercase tracking-wider mb-1 text-[10px]">Phone Number</label>
                <input 
                  type="tel" 
                  required
                  placeholder="+91 94191 00000"
                  value={sellerPhone}
                  onChange={(e) => setSellerPhone(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-300 rounded px-3 py-2 text-xs text-slate-900 focus:outline-none"
                />
              </div>
            </div>

            {/* Description Block */}
            <div className="bg-slate-50 p-3 rounded-lg border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <label className="text-[10px] font-bold text-slate-500 uppercase">Listing Description *</label>
                <button 
                  type="button"
                  onClick={handleAutoGenerateDescription}
                  disabled={isGeneratingAi}
                  className="text-[11px] font-bold text-amber-700 bg-amber-50 hover:bg-amber-100 px-2.5 py-1 rounded border border-amber-300 flex items-center gap-1 transition-colors"
                >
                  <Sparkles className="w-3 h-3 text-amber-600" />
                  <span>{isGeneratingAi ? 'Auto-writing...' : 'Auto-Generate Description'}</span>
                </button>
              </div>
              <textarea 
                rows={3}
                required
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Describe key features, society amenities, or PG mess facilities..."
                className="w-full bg-white border border-slate-300 rounded p-2 text-xs text-slate-900 focus:outline-none"
              />
            </div>

            <button 
              type="submit" 
              disabled={isSubmitting}
              className="w-full bg-amber-600 hover:bg-amber-700 text-white font-extrabold text-xs py-3 rounded transition-colors uppercase tracking-wider shadow-sm disabled:opacity-50"
            >
              {isSubmitting ? 'Uploading to Supabase DB & Storage...' : 'Publish Listing for Review'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
